- name: Add overlay filesystem module
  lineinfile: dest=/etc/modules state=present line="overlay" insertafter="EOF"
  tags: [docker]

- name: Load overlay module
  modprobe: name=overlay state=present
  tags: [docker]

- name: Add overlay kernel module
  command: echo "overlay" | sudo tee -a /etc/modules
  tags: [docker]